### ISSUE TITLE
How do I turn on sql logging so I can see what is executing? 

### ISSUE THREAD

**Issue by steppinrazor** [zonkyio/embedded-postgres#10]

**Comment by tomix26** [comment]
You can either enable logging directly on the PostgreSQL server, [or if you use an object-relational mapping tool, you can enable logging there](https://stackoverflow.com/questions/1710476/how-to-print-a-query-string-with-parameter-values-when-using-hibernate).

Example how to enable logging on the PostgreSQL server:
```java
@Rule
public SingleInstancePostgresRule pg = EmbeddedPostgresRules.singleInstance()
        .customize(builder -> builder
                .setServerConfig("log_statement", "all")
                .setServerConfig("log_destination", "csvlog")
                .setServerConfig("logging_collector", "on"));
```

**Comment by tomix26** [comment]
No response, I'm closing the issue.
