### ISSUE TITLE
[question] setting server options

### ISSUE THREAD

**Issue by kcris** [zonkyio/embedded-postgres#105]
Hi @tomix26 

I am running a huge test suite in scala, I ran into this error
```bash
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:postgresql://localhost:5432/postgres) for user 'postgres': FATAL: sorry, too many clients already
-------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 53300
Error Code : 0
Message    : FATAL: sorry, too many clients already
```

which quicly lead to the `max_connections` [issue](https://stackoverflow.com/questions/2757549/org-postgresql-util-psqlexception-fatal-sorry-too-many-clients-already), 

the default value for this option is apparently not good enough for me.

Running this in psql prompt
```bash
postgres=# show max_connections;
 max_connections 
-----------------
 300
(1 row)
```

shows I believe that the default is 300. 

So I was trying to set a higher value like this

```scala
  private lazy val postgres =
    EmbeddedPostgres
      .builder()
      .setDataDirectory(s"target/postgres/${getClass.getSimpleName}-${System.currentTimeMillis}")
      .setPort(5432)
      .setServerConfig("max_connections", "1000") //avoids???: FATAL: sorry, too many clients already
```

but if I run the psql prompt again it still shows 300 connections. So I guess I'm doing it wrong.

How can I set a custom `max_connections` programmaticcally to an instance of `EmbeddedPostgres` ??

Thanks

ps: this option has to be set before the server starts. Cannot change at runtime. See [this](https://www.postgresql.org/docs/current/runtime-config-connection.html)

pps: related options might have to be increased too, see [this](https://stackoverflow.com/questions/30778015/how-to-increase-the-max-connections-in-postgres)

**Comment by tomix26** [comment]
Hi @kcris, thanks for the question. I guess you are connecting to a wrong server or something like that. Because I've tested the same approach as you, and for me it works fine. Check the example below:

```java
    @Test
    public void testEmbeddedPg() throws Exception
    {
        try (EmbeddedPostgres pg = EmbeddedPostgres.builder().setServerConfig("max_connections", "1000").start();
             Connection c = pg.getPostgresDatabase().getConnection()) {
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("show max_connections");
            assertTrue(rs.next());
            assertEquals(1000, rs.getInt(1));
            assertFalse(rs.next());
        }
    }
```

**Comment by tomix26** [comment]
Hmm, I really don't know 🤔 For me, it works fine even if I set the data directory property.

```java
@Test
    public void testEmbeddedPg() throws Exception
    {
        try (EmbeddedPostgres pg = EmbeddedPostgres.builder()
                .setDataDirectory("target/postgres/EmbeddedPostgresTest-" + System.currentTimeMillis())
                .setServerConfig("max_connections", "1000")
                .start();
             Connection c = pg.getPostgresDatabase().getConnection()) {
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("show max_connections");
            assertTrue(rs.next());
            assertEquals(1000, rs.getInt(1));
            assertFalse(rs.next());
        }
    }
```

**Comment by kcris** [comment]
it's not `setDataDirectory` that causes the issue as I first suspected. 

It's `setPort`. Can you please try that one? Thanks a lot @tomix26

**Comment by tomix26** [comment]
Even with the port set, it still works as expected. As I said at the beginning, you're probably connecting to a different server running locally on the same port. So if you want my further assistance, check that there is no postgres process running locally and attach a reproducer of the problem to make the investigation easier.

**Comment by kcris** [comment]
that's not the case.

Above it's actual code, starting the server and immediately connecting to it. 

It's your example with just added `setPort` and `setDataDirectory`. 

Nevermind. Thanks again.

**Comment by kcris** [comment]
you were correct. Port 5432 was already listening. 

No idea how that can happen, since two apps cannot listen to the same port number 

and EmbeddedPostgres never complained about it (so I did not checked until now)

But that's what happens, there was 'another' 5432 already listening. Weird. 

Thanks @tomix26

**Comment by tomix26** [comment]
Ok, thanks for letting me know 👍
