### ISSUE TITLE
Fails on Windows ARM

### ISSUE THREAD

**Issue by benstpierre** [zonkyio/embedded-postgres#116]
Your app is amazing but I am unable to use i on windows for arm which is slowly becoming more popular.  There is no official postgres build for windows on arm yet but the x64 binaries should still work fine on arm windows.  I think you could adjust the code to use x88 or x64 binaries on windows arm fairly easily.

**Comment by benstpierre** [comment]
I literally just added this hack in and now it works...
![image](https://github.com/zonkyio/embedded-postgres/assets/1399854/fa8d7fe5-412c-4f15-98af-752bc15145a3)

**Comment by tomix26** [comment]
You’re right, thanks for the idea. I’m going to implement it to the next version.
