### ISSUE TITLE
Support for PostGIS/Geospatial?

### ISSUE THREAD

**Issue by amracel** [zonkyio/embedded-postgres#118]
Our code uses the PostGIS library, which doesn't seem to be included with this. Is there a way to add it?

**Comment by tomix26** [comment]
There is unofficial support for PostGIS provided by the community. It supports Windows and Linux platforms only, and I'm not sure if it's up to date and functional anymore. Also, there are no prebuilt packages available, and you would have to build it on your own by following the instructions here: https://github.com/zonkyio/embedded-postgres-binaries#build-only-a-single-binary
