### ISSUE TITLE
Changing the directory where the initdb is unpacked

### ISSUE THREAD

**Issue by pal548** [zonkyio/embedded-postgres#120]
Hello, we're facing an issue running build with Jenkins, `Cannot run program "/tmp/embedded-pg/PG-cb4c5b55707c145bb9aa5d2425d52f0c/bin/initdb": error=2, No such file or directory` 

Due to security reasons we can not write to `/tmp`, so is it possible to change the directory where the initdb is unpacked?

**Comment by tomix26** [comment]
Hi @pal548, thanks for the question. You can change the directory either by using the `ot.epg.working-dir` system property or by passing additional configuration in form of `EmbeddedPostgres.Builder` and setting the `overrideWorkingDirectory` property to any path you want.

**Comment by pal548** [comment]
It works, thanks a lot.
