### ISSUE TITLE
Upgrade org.apache.commons:commons-compress to 1.26.0 due to Infinite loop problem

### ISSUE THREAD

**Issue by lesiak** [zonkyio/embedded-postgres#127]
https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHECOMMONS-6254296

Infinite loop Affecting [org.apache.commons:commons-compress](https://security.snyk.io/package/maven/org.apache.commons%3Acommons-compress) package, versions [1.3,1.26.0)

**How to fix?**
Upgrade org.apache.commons:commons-compress to version 1.26.0 or higher.

**Overview**
[org.apache.commons:commons-compress](https://github.com/apache/commons-compress) is an API for working with compression and archive formats.

Affected versions of this package are vulnerable to Infinite loop due to the improper handling of certain inputs during the parsing of dump files. An attacker can cause the application to enter an infinite loop by supplying crafted inputs.

**Comment by tomix26** [comment]
Thank you for your contribution 👍
