### ISSUE TITLE
2.1.0 - Not available ?

### ISSUE THREAD

**Issue by lapsus63** [zonkyio/embedded-postgres#138]
Hello, This milestone is not available from Releases, will it be soon ?

**Comment by lapsus63** [comment]
(and maven central ?)

**Comment by tomix26** [comment]
If you're referring to https://github.com/zonkyio/embedded-postgres/milestone/19?closed=1, this version hasn't been released yet. I'll try to do that during this or next week.

**Comment by tomix26** [comment]
I'm sorry, but I'm going to release the new version next week after the out-of-cycle release of PostgreSQL, which fixes the found regressions (#140).

**Comment by lapsus63** [comment]
Hello,

Thanks for the update :)
I found a workaround using the current version (I excluded the conflicting
library from the dependency in thepom.xml and everything looks fine).

Good luck,
Best regards


Le sam. 16 nov. 2024 à 13:39, Tomáš Vaněk ***@***.***> a
écrit :

**Comment by tomix26** [comment]
The new version has been released.
