### ISSUE TITLE
Changing db schema in embedded-postgres doesn't work

### ISSUE THREAD

**Issue by piotrkot** [zonkyio/embedded-postgres#24]
I'm using embedded-postgres in version 1.2.6.
Before one test I create a schema - `schema_1`.
Later in my test I can successfully list the schemas with
`select schema_name from information_schema.schemata;`

But changing schema with
`SET SCHEMA 'schema_1'` or
`SELECT set_config('search_path', 'schema_1', false)`
doesn't work.
My current schema (`SELECT current_schema()`) still remains `public`.

I can successfully change the schema with either command on my local postgres installation.

**Comment by tomix26** [comment]
I tested it and works as expected. Please make sure you are calling all statements in a single transaction.

My sample test:
```java
public class SchemaTest {

    @Rule
    public SingleInstancePostgresRule epg = EmbeddedPostgresRules.singleInstance();

    @Test
    public void changeSchema() {
        DataSource dataSource = epg.getEmbeddedPostgres().getPostgresDatabase();

        DataSourceTransactionManager transactionManager = new DataSourceTransactionManager(dataSource);
        TransactionTemplate transactionTemplate = new TransactionTemplate(transactionManager);
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);

        String currentSchema = transactionTemplate.execute(transactionStatus -> {
            jdbcTemplate.execute("CREATE SCHEMA test");
            jdbcTemplate.execute("SET search_path TO test");
            return jdbcTemplate.queryForObject("SELECT current_schema()", String.class);
        });

        assertEquals("test", currentSchema);
    }
}
```

**Comment by CaioCris** [comment]
Hi tomix26, I think I know what piotrkot is going through cause I do had the same issue using the 
`SELECT set_config('keys.private', '${keys.private}', false);`

Actually I didn't reach a solution for this case, but I can tell you some of my tries:

**Comment by tomix26** [comment]
Hi @CaioCris, sorry for the late response.

1. The `spring.datasource.hikari.connection-init-sql` property cannot be used for this purpose because the embedded postgres library uses its own data source that not honor this property. So the specified sql statement is not executed.

2. When you used the statement in a flyway migration, did you have a placeholder configured for the  `${keys.private}` variable? See https://flywaydb.org/documentation/placeholders for more info.

Further, I modified my example above and tried to use `SELECT set_config('search_path', 'test', false)` statement instead and everything is still working fine.
```java
public class SchemaTest {

    @Rule
    public SingleInstancePostgresRule epg = EmbeddedPostgresRules.singleInstance();

    @Test
    public void changeSchema() {
        DataSource dataSource = epg.getEmbeddedPostgres().getPostgresDatabase();

        DataSourceTransactionManager transactionManager = new DataSourceTransactionManager(dataSource);
        TransactionTemplate transactionTemplate = new TransactionTemplate(transactionManager);
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);

        String currentSchema = transactionTemplate.execute(transactionStatus -> {
            jdbcTemplate.execute("CREATE SCHEMA test");
            jdbcTemplate.execute("SELECT set_config('search_path', 'test', false)");
            return jdbcTemplate.queryForObject("SELECT current_schema()", String.class);
        });

        assertEquals("test", currentSchema);
    }
}
```

**Comment by tomix26** [comment]
Closing the issue, feel free to reopen it if needed.
