### ISSUE TITLE
Embedded-postgres in a standalone Java application

### ISSUE THREAD

**Issue by zundarik** [zonkyio/embedded-postgres#26]
How to use embedded-postgres in a standalone Java application and to save the database in a file / directory? I need to run a Java application on windows / linux without installing posgresql server. Use not for tests, but for a small database.

**Comment by tomix26** [comment]
You could use lower-level api to create a database, see the example below. However, the library is intended for testing-only purposes and I really do not recommend using it in production deployment. Here is more information: https://github.com/zonkyio/embedded-database-spring-test/issues/49#issuecomment-485100268

```
@Configuration
public class DatabaseConfiguration {

    @Bean
    public DataSource dataSource() {
        Builder databaseBuilder = EmbeddedPostgres.builder();
        databaseBuilder.setDataDirectory("/path/to/database");
        databaseBuilder.setCleanDataDirectory(false);
        EmbeddedPostgres postgres = databaseBuilder.start();
        return postgres.getPostgresDatabase();
    }
}
```

**Comment by tomix26** [comment]
No response, I'm closing the issue.
