### ISSUE TITLE
executing test cases in embedded postgres in maven pre-integration-test phase

### ISSUE THREAD

**Issue by rameshjarabana** [zonkyio/embedded-postgres#30]
Hi Team,

Project: Spring boot 2.0, Maven, Zonky Embedded Postgres,Open Api3.0

I am using Zonky embedded Postgres for JUnit DAO test cases and its working fine in maven build.

Now I have a requirement to integrate open API into spring boot so I have added embedded profiles in the maven pre-integration-test phase to be available for test cases.

But while executing maven pre-intergration-test phase spring boot application is loading H2 database by default in place of embedded postgres , can someone help to find the solution for this problem wether do I need to do any extra configuration to load postgres in place of H2.

**Comment by tomix26** [comment]
Hi @rameshjarabana, have you tried this project: https://github.com/zonkyio/embedded-database-spring-test?

**Comment by rameshjarabana** [comment]
yes, I am using the same and its working fine in normal maven build cycle. But issue while executing maven pre-integration-test phase. i have configured embedded like below but still,default H2 is loading.
<execution>
            <id>pre-integration-test</id>
            <goals>
              <goal>start</goal>
            </goals>
            <configuration>
              <mainClass>XXXXXXXXXXXXXXXXXXXXXX</mainClass>
              <useTestClasspath>true</useTestClasspath>
              <folders>
                <folder>${project.build.testOutputDirectory}</folder>
              </folders>
              <environmentVariables>
                <spring.profiles.active>embeddedpostgres</spring.profiles.active>
              </environmentVariables>
            </configuration>
          </execution>

**Comment by tomix26** [comment]
I think there is a solution to your problem: https://github.com/zonkyio/embedded-database-spring-test/issues/49#issuecomment-485100268

**Comment by tomix26** [comment]
No response, I'm closing the issue.
