### ISSUE TITLE
Add to documentation how to change PostgreSQL version using Gradle

### ISSUE THREAD

**Issue by mfvanek** [zonkyio/embedded-postgres#31]
Hi there,
could you please add some tips to readme file about using this project with Gradle.

The main issue is how to change PostgreSQL version.
There are several ways to do it depending on used Gradle version.

**For Gradle 4.6+** you have to activate feature **IMPROVED_POM_SUPPORT** in **settings.gradle** file.
`enableFeaturePreview('IMPROVED_POM_SUPPORT')`
And then add the following rows to your build.gradle file
```
testImplementation 'io.zonky.test.postgres:embedded-postgres-binaries-bom:11.7.0'
testImplementation 'io.zonky.test:embedded-postgres:1.2.6'
```

**For Gradle 5+** activation of the additional feature is no longer required. You can use 'enforcedPlatform':
```
testImplementation 'io.zonky.test:embedded-postgres:1.2.6'
testImplementation enforcedPlatform('io.zonky.test.postgres:embedded-postgres-binaries-bom:11.7.0')
```

I think it would be very helpful for developers.

**Comment by tomix26** [comment]
Hi, you're right, I'll update the readme. Thanks.
