### ISSUE TITLE
How to connect to instance with psql?

### ISSUE THREAD

**Issue by velbur** [zonkyio/embedded-postgres#37]
Can i create an instance something like
```java
final EmbeddedPostgres pg = EmbeddedPostgres.start();
```
and connect to it with psq?
`
psql -h 127.0.0.1 -U postgres -p 5432 -d postgres
`

**Comment by tomix26** [comment]
Yes, you can. All you need to do is set a port number when initializing the postgres instance. Because if the port parameter is not specified, a random port number is generated.

`EmbeddedPostgres pg = EmbeddedPostgres.builder().setPort(5432).start();`

**Comment by velbur** [comment]
Thank you for information about port nuber. But is it possible to specify that it waits for connection?

**Comment by tomix26** [comment]
After completing the `start` method, the database should be ready to connect.

**Comment by velbur** [comment]
Example code.

`
public class Main {
    public static void main(String[] args) throws IOException, SQLException {
        EmbeddedPostgres pg = EmbeddedPostgres.builder().setPort(5432).start();
    }
}
`
it active only one or two seconds

**Comment by tomix26** [comment]
This is because the database is running only while the java process is running. When the java process is terminated then the all postgres instances created by the java process are terminated too.

The following solution is a bit naive, but it should work:
```
public class Main {
    public static void main(String[] args) throws IOException, SQLException {
        EmbeddedPostgres pg = EmbeddedPostgres.builder().setPort(5432).start();
        Thread.sleep(Long.MAX_VALUE); // waits forever
    }
}
```

**Comment by velbur** [comment]
Maybe somehow possible save  state of database and pass structure to new instance of embedded posgres?

**Comment by tomix26** [comment]
This library is primarily intended for integration testing, so from my point of view it is not needed.

**Comment by velbur** [comment]
Ok, thanks a lot for the answers.
