### ISSUE TITLE
Class org.junit.rules.ExternalResource not found - continuing with a stub.

### ISSUE THREAD

**Issue by tymm** [zonkyio/embedded-postgres#38]
When trying to use Flyway migration with embedded-postgres, I get the following error:
```
Class org.junit.rules.ExternalResource not found - continuing with a stub.
[error]           EmbeddedPostgresRules.preparedDatabase(
[error]           ^
```

What am I doing wrong?

**Comment by tomix26** [comment]
Are you using junit4? `EmbeddedPostgresRules` is intended for use in junit4 tests. If you are using junit5, you need to use `EmbeddedPostgresExtension` instead. Other testing frameworks are not supported at this moment. Check the following issue for more information about junit5 support: https://github.com/zonkyio/embedded-postgres/issues/34

**Comment by tymm** [comment]
Thanks. No, I'm not using junit at all.
But turns out that I can just use `getPostgresDatabase` to get the `DataSource` and with that use Flyway as normal for migration.
