### ISSUE TITLE
How to set defaultAutoCommit

### ISSUE THREAD

**Issue by TonyWeston** [zonkyio/embedded-postgres#44]
Hi - is there a way of setting defaultAutoCommit?

**Comment by tomix26** [comment]
Hey, is this question related to this library? The [postgres configuration](https://github.com/postgres/postgres/blob/master/src/backend/utils/misc/postgresql.conf.sample) does not offer any similar parameter, so it is probably a client configuration and therefore not related to embedded postgres. I'm closing the issue for now, feel free to reopen it if you think I missed something.
