### ISSUE TITLE
v12.1.0 on RHEL 7.8 x86_64?

### ISSUE THREAD

**Issue by shrimp3r** [zonkyio/embedded-postgres#51]
How can  I use a Postgres version newer that the default bundled 10.11 on x86_64? The "embedded-postgres-binaries" only provides 32bit Linux bundles - which I could run on 64-bit Linux, however it seems the code to locate the bundle searches by the x86_64 architecture string reported by my OS and therefore won't pickup the postgres-linux-x86_32.txz bundle.

Update: Looking at this a little bit further, I could implement my own PgBinaryResolver to locate the x86_32 bundle, even if my system if x86_64 - just wanna check if I'm making a simple mistake before I go down that route.

**Comment by shrimp3r** [comment]
Closing issue, I just needed to specify [io.zonky.test.postgres/embedded-postgres-binaries-linux-amd64](url) in my pom, which replaces the default 10.11 version on my classpath.

**Comment by tomix26** [comment]
Yes, exactly.
