### ISSUE TITLE
embedded-postgres on Apple Silicon (M1) issue

### ISSUE THREAD

**Issue by drej1** [zonkyio/embedded-postgres#52]
Hi there,

thanks for the great work in the first place, we were using embedded Postgres for a while now.

Now I switched to a MacBook Pro with the new M1 SoC which has arm64 architecture.
I debugged `DefaultPostgresBinaryResolver#getPgBinary` and the line
```java
Resource resource = findPgBinary(normalize(format("postgres-%s-%s.txz", system, architecture)));
```
does not find any binary because it is searching for `postgres-darwin-arm_64.txz`which I didn't find in https://mvnrepository.com/artifact/io.zonky.test.postgres

I assume there will be no release of Postgres for Darwin arm64 soon so is there a way to load the Darwin-amd64 embedded Postgres?

Dependencies we use:
```
compile("io.zonky.test:embedded-database-spring-test:1.6.1")
dependencyManagement {
        imports {
            mavenBom 'io.zonky.test.postgres:embedded-postgres-binaries-bom:9.6.16'
        }
    }
```

Thanks

**Comment by drej1** [comment]
@tomix26 ? :)

**Comment by tomix26** [comment]
Hi @drej1, thanks for the report. The mac os binaries are actually [EnterpriseDB binaries](https://www.enterprisedb.com/download-postgresql-binaries) but in reduced and repacked form. So now we are waiting for EnterpriseDB to release binaries for M1 architecture.

**Comment by drej1** [comment]
@tomix26 thanks for the info. Is there any roadmap on EnterpriseDB for supporting M1? If not, won't there be any workaround to support M1 in the meantime?
I did a local workaround for our project. It's very primitive :D 
I duplicated `io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver` and the only change is in `#getPgBinary` as follows:
```java
@Override
public InputStream getPgBinary(String system, String machineHardware) throws IOException {
    String architecture = ArchUtils.normalize(machineHardware);
    String distribution = LinuxUtils.getDistributionName();

    log.info("Detected distribution: '{}'", Optional.ofNullable(distribution).orElse("Unknown"));

    if (distribution != null) {
        Resource resource = findPgBinary(normalize(format("postgres-%s-%s-%s.txz", system, architecture, distribution)));
        if (resource != null) {
            log.info("Distribution specific postgres binaries found: {}", resource.getFilename());
            return resource.getInputStream();
        } else {
            log.debug("Distribution specific postgres binaries not found");
        }
    }

    // START CHANGES
    if (system.equals("Darwin") && architecture.equals("arm_64")) {
        architecture = "x86_64";
    }
    // END CHANGES

    Resource resource = findPgBinary(normalize(format("postgres-%s-%s.txz", system, architecture)));
    if (resource != null) {
        log.info("System specific postgres binaries found: {}", resource.getFilename());
        return resource.getInputStream();
    }

    log.error("No postgres binaries were found, you must add an appropriate maven dependency "
              + "that meets the following parameters - system: {}, architecture: {}", system, architecture);
    throw new IllegalStateException("Missing postgres binaries");
}
```

This downloads and runs intel architecture based embedded DB which works fine on the M1.

**Comment by tomix26** [comment]
Unfortunately, I don't know about any roadmap, at least not yet 😞

Nevertheless, your solution seems great to me. Using rosetta to translate x86_64 binaries to arm64 architecture is good enough. But it should be possible to avoid implementing the custom resolver by setting the architecture via a system property: `-Dos.arch=x86_64`

**Comment by drej1** [comment]
Hmm it sounds interesting, I didn't know about this option. I will try to play with this. Other people on the team don't use M1 so I want to find some global solution for the project. Thanks for the tip.

I leave this open for the native support.

**Comment by okopok** [comment]
@tomix26 still didn't work, even with duplicated ```DefaultPostgresBinaryResolver```

**Comment by jedvardsson** [comment]
@okopok Here is what I have working on my M1.

```
@Bean
@ConditionalOnProperty(name = "spring.datasource.embedded", havingValue = "true")
public EmbeddedPostgres embeddedPostgres() throws IOException {
    return EmbeddedPostgres.builder()
            .setPgBinaryResolver((system, machineHardware) -> {
                var arch = system.equals("Darwin") && machineHardware.equals("aarch64") ? "x86_64" : machineHardware;
                return DefaultPostgresBinaryResolver.INSTANCE.getPgBinary(system, arch);
            })
            .start();
}
```

**Comment by mrioan** [comment]
Taking the response from @jedvardsson and modifying it for my case:
```
builder.setPgBinaryResolver((system, machineHardware) -> {
                            String arch = system.equals("Darwin") && machineHardware.equals("aarch64") ? "x86_64" : machineHardware;
                            return EmbeddedPostgres.class.getResourceAsStream(format("/postgresql-%s-%s.txz", system, arch));
                        }).start();
```

**Comment by tomix26** [comment]
I've just released version [1.3.0](https://github.com/zonkyio/embedded-postgres/releases/tag/v1.3.0) that includes support for Rosetta 2 emulation out of the box. So it's no longer necessary to implement a custom binary resolver. Nevertheless, this is only a temporary solution and I'm still waiting for native binaries to become available.

**Comment by drej1** [comment]
Hi @tomix26 , how does it look with the native binaries? I have postgres installed via homebrew and it runs natively on Apple Silicon.

BTW the workaround works like a charm ;)

**Comment by jedvardsson** [comment]
@tomix26 What do you think about allowing the resolver to piggy-back on a locally installed Postgres or perhaps even a locally running Postgres.

**Comment by tomix26** [comment]
@drej1 Unfortunately, I have no new information, I'm still waiting for EnterpriseDB to release binaries for M1 architecture.

@jedvardsson I don't like it, because the main idea of this project is to have platform independent tests that can be easily run without any additional setup. If the tests were dependent on a local database installation, it would break this idea.

**Comment by tazle** [comment]
Looking at the EnterpriseDB binaries, they appear to be universal binaries and do include native arm64 variant:
```
% file psql 
psql: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
psql (for architecture x86_64):	Mach-O 64-bit executable x86_64
psql (for architecture arm64):	Mach-O 64-bit executable arm64
```

(this came from https://sbp.enterprisedb.com/getfile.jsp?fileid=1257912)

**Comment by timt** [comment]
I've just set up an M1 mac mini as a build server, and the Rosetta 2 emulation works really well, but only for a short while, then it seems like it stops working. (usually after about 10 builds have completed)

Has anyone else experienced this?

We are using the following dependencies/versions:

```
 "io.zonky.test" % "embedded-postgres" % "1.3.1"
 "io.zonky.test.postgres" % "embedded-postgres-binaries-darwin-amd64" % "11.13.0"

```
We see this warning just before it starts failing:

`[WARN] io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver pool-1-thread-1 - No native binaries supporting aarch64 architecture found. Trying to use binaries for amd64 architecture instead: 'postgres-darwin-x86_64.txz'. Make sure you have Rosetta 2 emulation enabled. Note that performance may be degraded.`

**Comment by GPJohnston** [comment]
> I've just set up an M1 mac mini as a build server, and the Rosetta 2 emulation works really well, but only for a short while, then it seems like it stops working. (usually after about 10 builds have completed)
> 
> Has anyone else experienced this?
> 
> We are using the following dependencies/versions:
> 
> ```
>  "io.zonky.test" % "embedded-postgres" % "1.3.1"
>  "io.zonky.test.postgres" % "embedded-postgres-binaries-darwin-amd64" % "11.13.0"
> ```
> 
> We see this warning just before it starts failing:
> 
> `[WARN] io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver pool-1-thread-1 - No native binaries supporting aarch64 architecture found. Trying to use binaries for amd64 architecture instead: 'postgres-darwin-x86_64.txz'. Make sure you have Rosetta 2 emulation enabled. Note that performance may be degraded.`

@timt 

I have been running into a similar issue as you today. It has built maybe 10-15 times before failing. 

I believe that log warning you have seen is just part of the process of selecting the binaries for the M1 architecture. 

After running the failing command In my shell I got this. 

```
running bootstrap script ... 2022-01-27 15:08:54.266 GMT [58511] FATAL:  could not create shared memory segment: Cannot allocate memory
2022-01-27 15:08:54.266 GMT [58511] DETAIL:  Failed system call was shmget(key=5432001, size=56, 03600).
2022-01-27 15:08:54.266 GMT [58511] HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded your kernel's SHMALL parameter.  You might need to reconfigure the kernel with larger SHMALL.
	The PostgreSQL documentation contains more information about shared memory configuration.
child process exited with exit code 1
```

Given that I have allocated more shared memory by executing the commands below (editing /etc/sysctl.conf did not help). I have seen an improvement, albeit likely temporary. 

```
sudo sysctl kern.sysv.shmmax=104857600
sudo sysctl kern.sysv.shmall=2560
```

**Comment by tomix26** [comment]
@timt Could you please test your build with version [11.14.0](https://mvnrepository.com/artifact/io.zonky.test.postgres/embedded-postgres-binaries-darwin-amd64/11.14.0)? This version should already contain native arm binaries, so maybe it could solve the problem. Note that the name of the dependency still refers to amd64 platform and when the build starts the library is still printing out the warning message. Don't worry, it's because the package contains binaries in Apple's universal format and the library doesn't take it into account.

**Comment by tomix26** [comment]
@GPJohnston I was also facing similar issue and in my case it was caused by many unfinished "zombie" processes that persisted on the machine. So please go through processes in activity monitor and check that there is no postgres process when the build is not running.

**Comment by GPJohnston** [comment]
@tomix26 I discovered the same when shared memory increase eventually bled out -> many processes running. Thank you.

**Comment by Eddy-Keith-McQueen** [comment]
I am still having issues with using this library.  I cloned the repo locally and just build and run it with `mvn clean install -U` and I get nothing but errors.

> [INFO] Running io.zonky.test.db.postgres.embedded.EmbeddedPostgresTest
892 [initdb:pid(34040)] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - no data was returned by command ""/private/var/folders/8p/lzpjm32n36vd92673p3ydyxw0000gn/T/embedded-pg/PG-a2a9bc65661eac6f108fc920268a87b3/bin/postgres" -V"
892 [initdb:pid(34040)] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - The program "postgres" is needed by initdb but was not found in the
893 [initdb:pid(34040)] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - same directory as "/private/var/folders/8p/lzpjm32n36vd92673p3ydyxw0000gn/T/embedded-pg/PG-a2a9bc65661eac6f108fc920268a87b3/bin/initdb".
893 [initdb:pid(34040)] INFO io.zonky.test.db.postgres.embedded.EmbeddedPostgres - Check your installation.

I thought this was supposed to have been fixed for M1 macs?  Am I missing something?  Is there something more I am supposed to do or configure to get this to work?

**Comment by timt** [comment]
@tomix26 I've tried upgrading to 11.14.0 as you suggested, but still have the same issue. 

On deeper investigation it is the same issue that @GPJohnston describes and his solution does work, although playing with the values, kern.sysv.shmmax, kern.sysv.shmall incrementally it seems they do not entirely fix this issue rather delays it. By setting the shmmax suitably high as suggested by @GPJohnston does buy us some time until this issue is properly resolved.

@tomix26 I've searched activity monitor for Zombie processes but can't see anything obvious - what name do these zombies have?

**Comment by tomix26** [comment]
I guess the name of the process is just "postgres" or something similar to this.

**Comment by michalmatovcik** [comment]
For me it started working after updating deps:

**_embedded-database-spring-test_** to version **2.1.1**
**_embedded-postgres-binaries-bom_** to version **14.2.0**

(current latest versions)

**Comment by tomix26** [comment]
Unfortunately I just realized that only the latest major version of [EnterpriseDB binaries](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads) includes native support for M1 architecture. So to fix the problem, try to upgrade to postgres 14 or later.

Related issue: https://github.com/zonkyio/embedded-postgres/issues/86

**Comment by rpoitras** [comment]
Thanks folks 👍.  Upgrading from 1.3.1 to [2.0.0](https://mvnrepository.com/artifact/io.zonky.test/embedded-postgres/2.0.0) fixed this for me.

In Gradle:

`testImplementation 'io.zonky.test:embedded-postgres:2.0.0'`
