### ISSUE TITLE
Allow running postgres in different authentication modes

### ISSUE THREAD

**Issue by NikolayMetchev** [zonkyio/embedded-postgres#55]
At the moment Embedded postgres runs in trust mode. However I would like to test our password changing code and cannot do so if the server doesn't reject logins with incorrect passwords.

Other modes are documented here:
https://www.postgresql.org/docs/10/auth-pg-hba-conf.html

**Comment by tomix26** [comment]
I think this is a fairly rare test scenario that only a few people will use. Therefore, I see no reason to implement this task. It's not worth the effort.

**Comment by tomix26** [comment]
But feel free to reopen the task if you have a different opinion.
