### ISSUE TITLE
Postgis?

### ISSUE THREAD

**Issue by misev** [zonkyio/embedded-postgres#59]
Question: is it possible to enable postgis in some way?

**Comment by tomix26** [comment]
You can compile the binaries manually and include postgis extension in the final package. Check the instructions here: https://github.com/zonkyio/embedded-postgres-binaries#build-only-a-single-binary. However, the only platform supported at the moment is Linux. Other platforms such as Windows or macOS are not supported and maybe never be.

**Comment by misev** [comment]
That's great, thank you for clarifying!
