### ISSUE TITLE
Duplicate postgres binaries

### ISSUE THREAD

**Issue by Quafadas** [zonkyio/embedded-postgres#62]
I got this library working briefly... but now I get this :-( ... 

```
[error] java.lang.IllegalStateException: Duplicate postgres binaries
[error]         at io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver.findPgBinary(DefaultPostgresBinaryResolver.java:78)
[error]         at io.zonky.test.db.postgres.embedded.DefaultPostgresBinaryResolver.getPgBinary(DefaultPostgresBinaryResolver.java:60)
[error]         at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.prepareBinaries(EmbeddedPostgres.java:784)
[error]         at io.zonky.test.db.postgres.embedded.EmbeddedPostgres.<init>(EmbeddedPostgres.java:133)
[error]         at io.zonky.test.db.postgres.embedded.EmbeddedPostgres$Builder.start(EmbeddedPostgres.java:583)
[error]         at example.backend.WithDbFramework.setup(WithDbFramework.scala:26)
```

Does anyone have a hint on what might be causing this or how to diagnose?

**Comment by tomix26** [comment]
Hi, there should also be another message `Detected multiple binaries of the same architecture: '...'` printing the list of problematic dependencies. This should give you an indication of where the problem is.

**Comment by Quafadas** [comment]
Hmmmm... I don't understand what happened, but the problem disappeared after killing off the build tool. 

I'll keep an eye out for this again and see if I can find the message you suggest - currently, I can't reproduce it, after having had it for an hour or so :-(... 

Thanks for the feedback.
