### ISSUE TITLE
Vulnerabilities from dependencies

### ISSUE THREAD

**Issue by lthoulon-locala** [zonkyio/embedded-postgres#88]
Hello,

there are a few vulnerabilities from the dependencies used by the project.
See them here: 
https://mvnrepository.com/artifact/io.zonky.test/embedded-postgres/1.3.1

Would it be possible to upgrade the dependencies ?
Thank you

**Comment by tomix26** [comment]
Hi @lthoulon-locala, thanks for letting me know. I'll take a look at it.

**Comment by lthoulon-locala** [comment]
Awesome thanks!
