### ISSUE TITLE
2.0.0 documentation / changelog

### ISSUE THREAD

**Issue by lthoulon-locala** [zonkyio/embedded-postgres#92]
Hello,

I see that a new major version has been released about a month ago (2.0.0) but I cannot find any information about what the changes are and if there are any breaking changes to be careful about as it's a new major version. The readme still seams to point to the 1.3.1 version.

Thanks

**Comment by tomix26** [comment]
Hi @lthoulon-locala, yes, you're right. Thanks for letting me know. I forgot, I'm sorry about that. The release notes have been updated.

**Comment by tomix26** [comment]
The readme has been also updated.
