### ISSUE TITLE
SUM(bigint) produces strange results on M1 mac in Docker

### ISSUE THREAD

**Issue by bcipriano** [zonkyio/embedded-postgres#99]
https://github.com/AcademySoftwareFoundation/OpenCue/pull/1199 has a full description of the issue.

Over on the OpenCue project we use embedded-postgres for unit tests.

Basically we are seeing strange results from `SUM(bigint)` on arm64+Docker where the result is wildly incorrect.

* Issue does not occur on other architectures.
* Issue does not occur when running directly on M1 -- only in Docker.
* I've tried a few different base images (gradle, almalinux) and that doesn't seem to change the result.
* I've tried a few different Postgres versions -- 11, 12, 14, 15 -- same issue on all of them.
* I haven't been able to reproduce the issue using the standard `postgres` Docker image.
* Changing our queries to `SUM(CAST(bigint as numeric))` fixes the issue.

Our [build.gradle](https://github.com/AcademySoftwareFoundation/OpenCue/pull/1199/files#diff-7e57ab670111c27c23069909d0cc32c88d266c9a1f3e6ca38052c973418146fe).

Any ideas here?

**Comment by bcipriano** [comment]
Thanks, I'll check these out when I can.

FWIW, the base image I'm using is `gradle:6.0.1-jdk13`, with [basically no modifications](https://github.com/bcipriano/OpenCue/blob/postgres-upgrade/cuebot/Dockerfile).

**Comment by tomix26** [comment]
@bcipriano Thank you very much for your pull request. All tests passed, everything seems to be working fine. New versions of the binaries have been released, so you can try them out. Great job!
